---
name: EPRI AI Lab
version: 1.0.0
schema: v1

# Define a custom anchor so that we can reuse gpt-oss model defaults
gpt_oss_defaults: &gpt_oss_defaults
  provider: openai
  model: openai/gpt-oss-120b
  apiBase: http://epr-ai-lno-p01.epri.com:8001/v1
  defaultCompletionOptions:
    contextLength: 65536 # max input + output tokens allowed (default: 32768)
    maxTokens: 32768 # max output tokens allowed, including reasoning (default: 4096); increased to mitigate bug in Continue's token counting logic
    temperature: 0.4 # lower temperature for code-related queries (default: 0.5)

# Define a custom anchor so that we can reuse Qwen3.5-35B-A3B model defaults
qwen3.6-35b-a3b_defaults: &qwen3.6-35b-a3b_defaults
  provider: openai
  model: Qwen/Qwen3.6-35B-A3B
  apiBase: https://qwen36-35b-a3b.ai-lab.epri.com/v1
  # set recommended options for code-related queries from: https://huggingface.co/Qwen/Qwen3.5-35B-A3B-FP8#using-qwen35-via-the-chat-completions-api
  defaultCompletionOptions:
    contextLength: 165536 # max input + output tokens allowed (default: 32768)
    maxTokens: 72768 # max output tokens allowed, including reasoning (default: 4096); increased to mitigate bug in Continue's token counting logic
    temperature: 0.6
    topP: 0.95
    topK: 20
  requestOptions:
    extraBodyProperties:
      min_p: 0.0
      presence_penalty: 0.0 
      repetition_penalty: 1.0
      chat_template_kwargs:
        enable_thinking: false 

models:
  - name: EPRI gpt-oss-120b (high)
    <<: *gpt_oss_defaults
    roles:
      - chat
      - edit
    capabilities:
      - tool_use # tool use required for Agent mode
    requestOptions:
      extraBodyProperties:
        reasoning_effort: high # high provides best quality
        include_reasoning: false # don't return reasoning tokens (mitigates bug in Continue)
  
  - name: "APPLY: EPRI gpt-oss-120b (medium)"
    <<: *gpt_oss_defaults
    roles:
      - apply
    requestOptions:
      extraBodyProperties:
        reasoning_effort: medium # medium is default reasoning
        include_reasoning: false # don't return reasoning tokens (mitigates bug in Continue)
    promptTemplates:
      apply: |
        <original_code>
        {{{original_code}}}
        </original_code>
        
        The following code was suggested as an edit:
        
        <new_code>
        {{{new_code}}}
        </new_code>

        Apply the new code to the original code. Leave existing comments in place unless changes require modifying them. Respond only with the final code. 

  - name: EPRI Qwen36-35b-a3b
    <<: *qwen3.6-35b-a3b_defaults
    roles:
      - chat
      - edit
      - apply
      - autocomplete
    capabilities:
      - tool_use # tool use required for Agent mode    